openapi: 3.0.0
servers: []
info:
  description: This API gives information on Augments, Units and Items
  version: "1.0.0"
  title: TFT Stats API
  contact:
    email: you@your-company.com
paths:
  /augment:
    post:
      tags:
        - augment
      summary: adds multiple statistic on the augment and other information
      operationId: receiver.post_augment_stats
      description: |
        adds augment's pick rate, placement, rarity, units that are used the most with
        and win rate with the augment based on each stage of the game
      responses:
        '200':
          description: augment are created and stats are added
        '400':
          description: augment stats are not added or augment is invalid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/augment'
        description: Reading item to add
  /unit:
    post:
      tags:
        - champions
      summary: adds unit, along with their cost and skills and other numbers
      operationId: receiver.post_units
      description: |
          creates the unit adding basic information of the unit
      responses:
        '200':
          description: champion is created
        '400':
          description: champion cannot be created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/unit'
        description: Reading champion to add   
  /health:
    get:
        tags:
          - health
        summary: gets info on an augment from history
        operationId: receiver.health
        description: Checks if service is running or if it's down
        responses:
          '200':
            description: Service is running 
components:
  schemas:
    augment:
      type: object
      required:
        - augment_id
        - name
        - rarity
        - placement
        - stage_picked
        - winrate
      properties:
        augment_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Built Different II
        rarity:
          type: string
          example: Gold
        placement:
          type: number
          example: 4.12
        stage_picked:
          type: string
          example: 2-1
        winrate:
          type: number
          example: 0.11
    unit:
      required:
        - unit_id
        - name
        - buy_cost
        - sell_cost
        - rarity
        - ability_name
        - stars
      properties:
        unit_id:
          type: string
          format: uuid
          example: 9e62a274-5afc-11ee-8c99-0242ac120002
        name:
          type: string
          example: Zeri
        buy_cost:
          type: integer
          example: 4
        sell_cost:
          type: integer
          example: 4
        rarity:
          type: string
          example: purple
        ability_name:
          type: string
          example: Surge
        stars:
          type: integer
          example: 1
      type: object