openapi: 3.0.0
servers: []
info:
  description: This API gives information on Augments, Units and Items
  version: "1.0.0"
  title: TFT Stats API
  contact:
    email: you@your-company.com

paths:
  /health:
    get:
      tags:
        - health check
      summary: returns health check status
      operationId: health.health_check
      description: returns a json result of all health checks on each service
      responses:
        '200':
          description: Returned health check
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/health_check'

components:
  schemas:
    health_check:
      type: object
      required:
        - receiver
        - storage
        - audit
        - processing
        - last_updated
      properties:
        receiver:
          type: string
          example: running
        storage:
          type: string
          example: running
        audit:
          type: string
          example: running
        processing:
          type: string
          example: running
        last_updated:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'
