pipeline {
    agent any
    
    stages {
      stage('Deploy') {
        steps {
                sshagent(credentials : ['9b469d5e-6263-4a41-b9a7-110010946377']) {
                    sh 'ssh azureuser@172.200.178.60'
                    sh "docker compose up -d"
                }
            }
        }
      }
}
