pipeline {
    agent any
    
    stages {
      stage('Deploy') {
        steps {
                sshagent(credentials : ['9b469d5e-6263-4a41-b9a7-110010946377']) {
                    sh 'ssh -o StrictHostKeyChecking=no user@hostname.com uptime'
                    sh 'ssh -tt azureuser@3855-benny'
                    sh "docker compose up -d"
                }
            }
        }
      }
}
