pipeline {
    agent any
    
    stages {
        stage('Deploy') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: "benny_ssh_key", keyFileVariable: 'SSH_KEY')]) {
                    sshagent(['benny_ssh_key']) {
                        sh "ssh -o StrictHostKeyChecking=no azureuser@172.200.178.60"
                        sh "cd 3855-app/deployment"
                        sh "docker compose up -d"
                    }
                }
            }
        }
    }
}
